name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run server tests
      run: cargo test --workspace --verbose

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

  client-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run client tests
      working-directory: client
      run: npm ci && npm run check

